<<<<<<< HEAD
// Generated by CoffeeScript 1.6.3
angular.module('ngBoilerplate.about', ['ui.state', 'placeholders', 'ui.bootstrap']).config([
  '$stateProvider', function($stateProvider) {
    return $stateProvider.state('about', {
      url: '/about',
      views: {
        main: {
          controller: 'AboutCtrl',
          templateUrl: 'about/about.tpl.html'
        }
      },
      data: {
        pageTitle: 'What is It?'
      }
    });
  }
]).controller('AboutCtrl', [
  '$scope', function($scope) {
    return $scope.dropdownDemoItems = ["The first choice!", "And another choice for you.", "but wait! A third!"];
  }
]);
=======
angular.module( 'ngBoilerplate.about', [
  'ui.state',
  'placeholders',
  'ui.bootstrap'
])

.config(function config( $stateProvider ) {
  $stateProvider.state( 'about', {
    url: '/about',
    views: {
      "main": {
        controller: 'AboutCtrl',
        templateUrl: 'about/about.tpl.html'
      }
    },
    data:{ pageTitle: 'What is It?' }
  });
})

.controller( 'AboutCtrl', function AboutCtrl( $scope ) {
  // This is simple a demo for UI Boostrap.
  $scope.dropdownDemoItems = [
    "The first choice!",
    "And another choice for you.",
    "but wait! A third!"
  ];
})

;
>>>>>>> fbb926390d590cb90d7ea67b2ee1564673b2d105
