// Generated by CoffeeScript 1.6.3
angular.module('ngBoilerplate', ['templates-app', 'templates-common', 'ngBoilerplate.home', 'ngBoilerplate.about', 'ui.state', 'ui.route']).config([
  '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
    return $urlRouterProvider.otherwise('/home');
  }
]).run(function() {}).controller('AppCtrl', [
  '$scope', '$location', function($scope, $location) {
    return $scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
      if (angular.isDefined(toState.data.pageTitle)) {
        return $scope.pageTitle = toState.data.pageTitle + ' | ngBoilerplate';
      }
    });
  }
]);
