// Generated by CoffeeScript 1.6.3
describe('AppCtrl', function() {
  return describe('isCurrentUrl', function() {
    var $location, $scope, AppCtrl;
    beforeEach(module('ngBoilerplate'));
    AppCtrl = null;
    $location = null;
    $scope = null;
    beforeEach(inject(function($controller, _$location_, $rootScope) {
      $location = _$location_;
      $scope = $rootScope.$new();
      return AppCtrl = $controller('AppCtrl', {
        $location: $location,
        $scope: $scope
      });
    }));
    return it('should pass a dummy test', inject(function() {
      return expect(AppCtrl).toBeTruthy();
    }));
  });
});
