<<<<<<< HEAD
// Generated by CoffeeScript 1.6.3
angular.module('ngBoilerplate', ['templates-app', 'templates-common', 'ngBoilerplate.home', 'ngBoilerplate.about', 'ui.state', 'ui.route']).config([
  '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
    return $urlRouterProvider.otherwise('/home');
  }
]).run(function() {}).controller('AppCtrl', [
  '$scope', '$location', function($scope, $location) {
    return $scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
      if (angular.isDefined(toState.data.pageTitle)) {
        return $scope.pageTitle = toState.data.pageTitle + ' | ngBoilerplate';
      }
    });
  }
]);
=======
angular.module( 'ngBoilerplate', [
  'templates-app',
  'templates-common',
  'ngBoilerplate.home',
  'ngBoilerplate.about',
  'ui.state',
  'ui.route'
])

.config( function myAppConfig ( $stateProvider, $urlRouterProvider ) {
  $urlRouterProvider.otherwise( '/home' );
})

.run( function run () {
})

.controller( 'AppCtrl', function AppCtrl ( $scope, $location ) {
  $scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams){
    if ( angular.isDefined( toState.data.pageTitle ) ) {
      $scope.pageTitle = toState.data.pageTitle + ' | ngBoilerplate' ;
    }
  });
})

;

>>>>>>> fbb926390d590cb90d7ea67b2ee1564673b2d105
