<<<<<<< HEAD
// Generated by CoffeeScript 1.6.3
/*
Tests sit right alongside the file they are testing, which is more intuitive
and portable than separating `src` and `test` directories. Additionally, the
build process will exclude all `.spec.js` files from the build
automatically.
*/

describe('home section', function() {
  beforeEach(module('ngBoilerplate.home'));
  return it('should have a dummy test', inject(function() {
    return expect(true).toBeTruthy();
  }));
});
=======
/**
 * Tests sit right alongside the file they are testing, which is more intuitive
 * and portable than separating `src` and `test` directories. Additionally, the
 * build process will exclude all `.spec.js` files from the build
 * automatically.
 */
describe( 'home section', function() {
  beforeEach( module( 'ngBoilerplate.home' ) );

  it( 'should have a dummy test', inject( function() {
    expect( true ).toBeTruthy();
  }));
});

>>>>>>> fbb926390d590cb90d7ea67b2ee1564673b2d105
